export var settings = [
    {
        objectKey:'Name',
        columnOrder:0
      },
      {
        objectKey:'Alias_Name',
        columnOrder:1
      },
      {
        objectKey:'RoundReq',
        columnOrder:2
      }
      ,{
        objectKey:'RoundNo',
        columnOrder:3
      }
      ,{
        objectKey:'ScheduleQty',
        columnOrder:4
      }
      ,{
        objectKey:'OkQty',
        columnOrder:5
      }
      ,{
        objectKey:'RejectedQty',
        columnOrder:6
      }
      ]